# call build with --buildarg GITUSER=gituser --buildarg GITPW=gitpw --build-arg GPU="TRUE"
FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04
ARG GITUSER
ARG GITPW
ARG GPU="FALSE"
ENV SUMO_HOME=/sumo 
ENV SUMOAI_HOME=/sumoai

RUN apt update && apt upgrade -y
RUN apt update && apt install -y \
	git \
	python3 \
	jq \
	curl \
	wget \
	unzip \
	python \
	autoconf \
	libproj-dev \
	libxerces-c-dev \
	libgdal-dev \
	libfox-1.6-dev \
	python3-tk \
	python3-pip \
	libsm6 \
	libxrender1 \
	libfontconfig1

# Sumo install
RUN wget https://github.com/eclipse/sumo/archive/`curl \
	--silent "https://api.github.com/repos/eclipse/sumo/tags" | jq -r '.[0].name'`.zip \
	&& unzip v*.zip \
	&& mv sumo* $SUMO_HOME \
	&& rm v*.zip

RUN cd $SUMO_HOME \
	&& make -f Makefile.cvs \
	&& ./configure \
	&& make

# Sumo-ai install
RUN git clone https://$GITUSER:$GITPW@github.com/INFLUENCEorg/sumoai.git $SUMOAI_HOME

RUN cd $SUMOAI_HOME/sumoai \
	&& pip3 install --upgrade setuptools \
	&& pip3 install wheel \
	&& python3 setup.py sdist bdist_wheel

RUN cd $SUMOAI_HOME/sumoai/dist \
	&& pip3 install sumoai*.tar.gz 

# Install tensorflow-gpu if we are using a GPU (i.e. when --build-arg GPU="TRUE")
RUN if [ "$GPU" = "TRUE" ] ; then pip3 uninstall -y tensorflow && pip3 install --upgrade tensorflow-gpu; else echo "No GPU"; fi
