parameters:
    # Common hyperparameters
    seed: null
    max_steps: 40

    environment:
        steps: 10
        robots: #initial robot positions
          - id: 'robot2'
            pos: 'random'
          - id: 'robot1'
            pos: 'random' 
          - id: 'robot3'
            pos: 'random' 
        tasks: ['random', 'random']  # initial task positions
        P_action_succeed: 
          LEFT: 0.9
          RIGHT: 0.9 
          ACT: 0.8 
          UP: 0.9 
          DOWN: 0.9
          robot1:
            LEFT: 0.2
            RIGHT: 0.2 
            ACT: 0.2 
            UP: 0.2 
            DOWN: 0.2
          robot2:
            LEFT: 0.2
            RIGHT: 0.2 
            ACT: 0.2 
            UP: 0.2 
            DOWN: 0.2
          robot3:
            LEFT: 0.2
            RIGHT: 0.2 
            ACT: 0.2 
            UP: 0.2 
            DOWN: 0.2
        P_task_appears: 1.0  # P(new task appears in step) 
        N_task_appears: 4
        allow_robot_overlap: True
        allow_task_overlap: True
        map: ['11111',
              '11111',
              '11111',
              '11111']
