parameters:
  all:
    mode: 'train'
    load: false
    name: 'Two_Grid_Test'
    algorithm: DQN
    port: 8000
    gui: false
    env_type: 'SUMO'

    max_steps: 2.0e+6
    max_episode_steps: 5.0e+3
    frame_height: 1000
    frame_width: 1500
    num_frames: 2 # 10
    skip_frames: 1
    gamma: 0.99
    learning_rate: 2.5e-4
    batch_size: 32
    memory_size: 100 # 30000
    train_frequency: 1
    save_frequency: 5.0e+4
    summary_frequency: 1.0e+4
    tensorboard: false
    iteration: -1
    episode: 0
    seedlist: [43, 44, 45]

    # DQN only
    freeze_interval: 30000
    double_dqn: True
    epsilon: 0.1

    ######################## SUMO SCEANRIO ########################

    # the scene
    scene: 'two_grid_H'
    tlphasesfile: 'two_grid_H.net.xml'

    # vehicle generation
    car_tm: 1000
    car_pr: 0.1

    # Yello light time
    y_t: 6

    # state representation
    box_bottom_corner: [0, 0]
    box_top_corner: [1500, 1000]
    resolutionInPixelsPerMeterX: 1
    resolutionInPixelsPerMeterY: 1
    state_type: 'ldm_state' # The type of state to use as input for the network. ('bin' (Position Matrix), 'bin_light' (Position Light Matrix), 'value' (Value Matrix))

    # routes
    route_starts: ['right_l1 l1_l0 l0_left', 'left_l0 l0_l1 l1_right', 'top_l0 l0_bottom', 'bottom_l0 l0_top', 'top_l1 l1_bottom', 'bottom_l1 l1_top']
    route_segments: []
    route_ends: []
    route_max_segments: 0
    route_min_segments: 0

    # I have no idea
    local_rewards: True
    waiting_penalty: False
    scaling_factor: 10 # for rescaling reward
    fast: false
    speed_dev: 0.0 # Can be used to vary the speeds of cars, according to a normal distribution with mean 1 and standard deviation speed_dev (SUMOs default is 0.1)

    # traffic light positions
    lightPositions: {"0":[[498.50, 507.24], [492.80, 498.38], [501.83, 492.18], [507.46, 501.57]], "1": [[998.50, 507.24], [992.59, 498.38], [1001.67, 492.18], [1007.44, 501.57]]}
